name: .NET Release

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./eCommerce.API/eCommerce.API.csproj

    - name: Build project
      run: dotnet build ./eCommerce.API/eCommerce.API.csproj --configuration Release --no-restore

    - name: Publish project
      run: dotnet publish ./eCommerce.API/eCommerce.API.csproj --configuration Release --output ./publish

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ecommerce-api
        path: ./publish
